---
title: "Deprecated"
output: html_notebook
---

# Models controlling for No Brainers

* These models have been deprecated due to *convergence issues* or *singular fit* issues

## Pooled SR model controlling for NoBrainers

```{r}

# Create model
SR2 <- glmer(PtResp ~ 1 + NoBrainers + SessionTime*Condition*LogLLA + SessionTime*Condition*LogBaserate + (1|PtID),
             family = binomial('probit'),
             data_SR
             )

# This model failed to converge. 
summary(SR2)

```

## AM-only model with NoBrainers (Singular fit)
```{r}


# Create model
SR_AM2 <- glmer(PtResp ~ 1 + NoBrainers + Condition*LogLLA + Condition*LogBaserate + (1|PtID),
             family = binomial('probit'),
             data_SR_AM
             )

# Print summary
summary(SR_AM2)


```

## PM-only model with NoBrainers (Singular fit)
```{r}


# Create model
SR_PM2 <- glmer(PtResp ~ 1 + NoBrainers + Condition*LogLLA + Condition*LogBaserate + (1|PtID),
             family = binomial('probit'),
             data_SR_PM
             )

# Print summary
summary(SR_PM2)


```